@endpoint = https://wnrj3o34vf.execute-api.eu-west-2.amazonaws.com/prod/

GET {{endpoint}}/hello
###


POST {{endpoint}}/spaces
Content-Type: application/json

{
	"location": "London",
	"name": "Best location"
}
###